pipeline update

diff --git a/.github/workflows/calculator_pipeline.yml b/.github/workflows/calculator_pipeline.yml
--- a/.github/workflows/calculator_pipeline.yml
+++ b/.github/workflows/calculator_pipeline.yml
@@ -6,9 +6,9 @@ name: CI
 on:
   # Triggers the workflow on push or pull request events but only for the "main" branch
   push:
-    branches: [ "main" ]
+    branches: ["main"]
   pull_request:
-    branches: [ "main" ]
+    branches: ["main"]
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -23,6 +23,27 @@ jobs:
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+
+      - name: setup Python
+        uses: actions/checkout@v2
+        with:
+          python-version: "3.9"
+
+      - name: install dependies
+        run: pip install -r BE/requirement.txt
+
+      - name: install Rest api
+        run: python BE/calculator.py --rest &
+
+      - name: install pytest
+        run: pytest --junit-xml=report.xml
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "**/build/test-results/test/TEST-*.xml"
+
       - uses: actions/checkout@v4
 
       - name: login to azure registery
@@ -33,8 +54,7 @@ jobs:
           password: ${{ secrets.PASSWORD }}
 
       # Runs a single command using the runners shell
-      
+
       # Runs a set of commands using the runners shell
       - name: Run and build docker image
         run: docker build --push --tag judevops.azurecr.io/nasir_jama_elmi-calculator BE/
-          
